[package]
name = "mdbook-alerts"
version = "0.1.0"
authors = ["Alisue <lambdalisue@gmail.com>"]
edition = "2021"

description = ""
repository = "https://github.com/lambdalisue/rs-mdbook-alerts"
license = "MIT"
readme = "README.md"
keywords = [ "mdbook", "preprocessor", "markdown", "github", "alerts", "callouts" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
